feat: Copy of tx.allowed_request_content_type initialization
coreruleset/nextcloud-rule-exclusions-plugin pull request #14
Opened 2023-03-21 12:05 UTC by azurit

As discussed on Slack, this is needed for proper modification of `tx.allowed_request_content_type` by exclusion rules. Plugins are currently running before CRS initialization so variables like `tx.allowed_request_content_type` needs to be initialized also by plugins if they are going to be modified.

2023-03-21 12:07 UTC, azurit commented
@dune73 Can you be so kind and look at this? Is this done by the way we agreed yesterday on Slack?

2023-03-25 14:36 UTC, theseion requested changes

2023-03-25 14:36 UTC, theseion commented on plugins/nextcloud-rule-exclusions-before.conf
> +# We need to initialize this also here because plugins runs before CRS initialization (this
```suggestion
# We need to initialize this also here because plugin setup runs before CRS initialization (this
```

2023-03-25 14:36 UTC, theseion commented on plugins/nextcloud-rule-exclusions-before.conf
> +# is a know limitation of current plugin implementation). Must be kept in sync with CRS
```suggestion
# is a known limitation of the current plugin architecture). Must be kept in sync with CRS
```

2023-03-25 14:41 UTC, theseion commented
We need the same for HTTP methods. Are you going to open that one too?

2023-03-25 14:42 UTC, azurit commented
Yes i just need an confirmation that this is the right way to do it.

2023-03-25 14:45 UTC, theseion commented
I believe it is. That was my take away from the discussion.

2023-03-25 15:41 UTC, theseion approved these changes

2023-03-25 15:46 UTC, merged

2023-03-27 09:09 UTC, dune73 commented
Sorry for being late to the show. I agree with the resolution.