Allow the PUT method globally in the deck app.
coreruleset/nextcloud-rule-exclusions-plugin pull request #58
Opened 2024-02-17 14:35 UTC by mivek

I updated the rule added in #53 to allow to `PUT` method when moving cards, un-assigning users and setting a due date.

2024-02-17 15:18 UTC, EsadCetiner requested changes

2024-02-17 15:18 UTC, EsadCetiner commented on plugins/nextcloud-rule-exclusions-before.conf
> +SecRule REQUEST_FILENAME "@rx /apps/deck/cards/[0-9]+" \
You should try to match as exact as you can for the URL path to minimize the chance of a bypass. Based on the URLs provided in your regression test, you should use this regular expression.
```suggestion
# When updating a card
# Moving a card in deck
# Unassigning a user from a card
# Setting a due date on a card
SecRule REQUEST_FILENAME "@rx /apps/deck/cards/[0-9]+(?:/reorder|/unassign)?$" \
```
https://regexr.com/7s4pl

2024-02-18 03:13 UTC, EsadCetiner approved these changes

2024-02-18 07:05 UTC, theseion commented on tests/regression/nextcloud-rule-exclusions-plugin/9508810.yaml
> +  - test_title: 9508810-2
```suggestion
  - test_title: 9508810-3
```

2024-02-18 07:05 UTC, theseion commented on tests/regression/nextcloud-rule-exclusions-plugin/9508810.yaml
> +              User-Agent: OWASP ModSecurity Core Rule Set
```suggestion
              User-Agent: OWASP CRS
```

2024-02-18 07:06 UTC, theseion commented on tests/regression/nextcloud-rule-exclusions-plugin/9508810.yaml
> +              User-Agent: OWASP ModSecurity Core Rule Set
```suggestion
              User-Agent: OWASP CRS
```

2024-02-18 07:06 UTC, theseion commented on tests/regression/nextcloud-rule-exclusions-plugin/9508810.yaml
> +      Target: description
```suggestion
```

2024-02-18 07:06 UTC, theseion commented on tests/regression/nextcloud-rule-exclusions-plugin/9508810.yaml
> +      Unassigning a user from a card.
```suggestion
```

2024-02-18 07:06 UTC, theseion commented on tests/regression/nextcloud-rule-exclusions-plugin/9508810.yaml
> +    desc: |
```suggestion
    desc: Unassigning a user from a card
```

2024-02-18 07:07 UTC, theseion commented on tests/regression/nextcloud-rule-exclusions-plugin/9508810.yaml
> +      Target: description
```suggestion
      Target: json.data
```

2024-02-18 07:07 UTC, theseion commented on tests/regression/nextcloud-rule-exclusions-plugin/9508810.yaml
> +      Setting a due date to a card.
```suggestion
      Setting a due date on a card.
```

2024-02-18 12:54 UTC, theseion approved these changes

2024-02-18 12:55 UTC, merged