fix: text editor in public share and token related FPs
coreruleset/nextcloud-rule-exclusions-plugin pull request #59
Opened 2024-02-17 14:47 UTC by EsadCetiner

This PR mostly fixes issues with session tokens that are only an issue at PL-2 and above, but there is a fix for using the markdown test editor in public shares. 
The tests for some of these rules were very large(This PR would've been above 700 lines, but now it's about 300), so I refactored them by using a ``|`` to test against multiple URIs with the same payload, but for whatever reason the nginx regression tests are failing while the apache tests are passing.

2024-02-17 19:58 UTC, theseion commented
I'll check it out tomorrow.

2024-02-18 06:56 UTC, theseion commented
This will create an illegal request:
```
uri: |
  uri1
  uri2
```

This is the same issue you had with the regular expressions: the vertical bar `|` in YAML means "verbatim string", not "list". The request generated from the above would look like this:
```
PUT /apps/text/session/create
/apps/text/public/session/create
 HTTP/1.1
Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5
Connection: close
Content-Length: 0
Host: localhost
User-Agent: OWASP CRS
```

As you can see, the URIs are used as the request URI _verbatim_, including line breaks.

There is currently no way to run the same test against multiple URIs (would be great though). You could use multiple stages per test but that only makes a small difference and isn't what stages are designed for. For now, you don't have any other option than to duplicate tests for different URIs.

2024-02-18 07:00 UTC, theseion commented
I've created a feature request in go-ftw: https://github.com/coreruleset/go-ftw/issues/256

2024-02-18 07:31 UTC, EsadCetiner commented
@theseion Thanks for the explanation, guess we'll have to live with it for now until go-ftw adds support for what I'm trying to do.

2024-02-18 12:52 UTC, theseion requested changes

2024-02-18 19:36 UTC, EsadCetiner commented on plugins/nextcloud-rule-exclusions-before.conf
> +# This value is null for non public shares
It shows up like this in inspect element with the null greyed out ``token: null``

2024-02-18 19:43 UTC, EsadCetiner commented on tests/regression/nextcloud-rule-exclusions-plugin/9508314.yaml
> +            data: "json.awareness=lsbuas8df0bsd0789fsd07a98fnnuin="
looks like your right, good catch. The ``+`` and ``/`` and even the ``=`` would sometimes not show up so that throwed me off.

2024-02-18 20:05 UTC, theseion commented on plugins/nextcloud-rule-exclusions-before.conf
> +# This value is null for non public shares
That would be `{"x": null}`, for example (`JSON.parse('{"x": null}')`). So the string value you'd need to test for would be, for example, `json.toke=null`.

2024-02-18 20:08 UTC, EsadCetiner commented on plugins/nextcloud-rule-exclusions-before.conf
> +# This value is null for non public shares
that value shouldn't cause any false positive though, even at PL-4.

2024-02-18 20:18 UTC, theseion commented on plugins/nextcloud-rule-exclusions-before.conf
> +# This value is null for non public shares
Yes... So why do you need the rule then?

2024-02-18 20:19 UTC, theseion commented on plugins/nextcloud-rule-exclusions-before.conf
> +# This value is null for non public shares
What does the log say excatly?

2024-02-19 07:20 UTC, EsadCetiner commented on plugins/nextcloud-rule-exclusions-before.conf
> +# This value is null for non public shares
Yes, that's what the rule is trying to do. I added your suggestion to make it clearer.

2024-02-19 17:33 UTC, theseion approved these changes

2024-02-19 17:33 UTC, merged