fix: sqli fp with tokens and special characters
coreruleset/nextcloud-rule-exclusions-plugin pull request #79
Opened 2024-06-15 23:20 UTC by EsadCetiner

2024-06-18 19:00 UTC, theseion requested changes

2024-06-18 19:00 UTC, theseion commented on tests/regression/nextcloud-rule-exclusions-plugin/9508312.yaml
> +  - test_title: 9508312-28
```suggestion
  - test_title: 9508312-29
```

2024-06-18 19:00 UTC, theseion commented on tests/regression/nextcloud-rule-exclusions-plugin/9508420.yaml
Don't you want to keep these tests? I'd just move them to the new rule.

2024-06-19 00:11 UTC, EsadCetiner commented on tests/regression/nextcloud-rule-exclusions-plugin/9508420.yaml
Most of these tests are testing the same payload, just against different URL paths. I did notice I missed one payload so I'll add that.

2024-06-19 04:32 UTC, theseion approved these changes

2024-06-19 04:37 UTC, merged