fix: use case insensitivity for public shares when entering passwords
coreruleset/nextcloud-rule-exclusions-plugin pull request #82
Opened 2024-07-11 00:07 UTC by EsadCetiner

Nextcloud has recently renamed the endpoint for entering passwords in public shares from ``/s/random/authenticate/showShare`` to ``/s/random/authenticate/showshare`` causing the rule that handles false positives with passwords to no longer match. This PR makes that rule case insensitive.

2024-07-11 18:50 UTC, theseion requested changes

2024-07-11 18:50 UTC, theseion commented on tests/regression/nextcloud-rule-exclusions-plugin/9508171.yaml
> +    desc: Entering password on a public share
```suggestion
    desc: Entering password on a public share (Nextcloud < v....)
```

2024-08-10 08:26 UTC, azurit approved these changes

2024-08-10 08:27 UTC, azurit commented
@theseion Is this ready to merge?

2024-08-10 09:48 UTC, theseion approved these changes

2024-08-10 09:49 UTC, merged